db:
  username: "{db_username}"
  password: "{db_password}"
  name: "{db_name}"
  host: "db"
  port: "{port}"



mattermost:
  http_host: "https://{mattermost_host}"
  api_location: "/api/v4/"
  api_version: "4"
  token: "{mm_token}"
  id: "{mm_id}"
  filter_messages_contains: "some_substring"
  listen_channels:
    - "{channel_for_listen_1}"
    - "{channel_for_listen_2}"
  target_events_processors:
    - posted:
       - "save"
       - "response"
    - hello:
       - "log"
